config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'

  get '/help',  to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # this is for fixtures to have a secured password
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid Email/Password Combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_title(title = '')
    base_title = 'Pithugram'
    if title.empty?
      base_title
    else
      "#{title}|#{base_title}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <nav>
    <ul>
      <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "About", about_path %></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="#"><img src="/assets/symbol.jpg" class="logo">
            <h1 class="heading"> Pithugram</h1></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to 'Users', "#" %></li>
        <li><%= link_to 'Profile', current_user %></li>
        <li><%= link_to 'Edit', "#" %></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Signup', signup_path %></li>
        <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div class="row">
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end  %>

app/views/static_pages/about.html.erb
<% provide(:title,'About') %>
<h1>About</h1>
<div class="container">
  <div class="row">
<p><h3>Pithugram</h3> is an online news and social networking service where users post and
  interact with messages, "tweets". Registered users can post tweets,
  but those who are unregistered can only read them. Users access Pithugram through its website interface.
</p>
</div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title,'Help') %>
<h1>Help</h1>
<div class='container'>
<div class="row">
<h3>What is Pithugram?</h3>
<p>Pithugram is the place to find out about what’s happening in the world right now.
   Whether you’re interested in music, sports, politics, news, celebrities, or everyday moments—come
   to Pithugram to see and join in on what’s happening now.</p>
</div>
<div class="row">
<h3>What do I use Pithugram for?</h3>
<p>While everyone experiences Pithugram differently, here are a few areas that might interest you to help you get started.
</p>
 <p><b>News and politics:</b> Get the latest on local and global news, watch political events as they unfold,
   and take a part in communities and social movements.</p>
 <p><b>Sports:</b> From the Olympics to the NFL draft, get real-time updates, see what the star players have t
   o say, and connect with fans around the world.</p>
 <p><b>Pop culture:</b> See what your favorite celebrities are up to by following them on Pithugram
   and joining in on the conversation.</p>
 <p><b>Influencers:</b> Find out what thought-leaders and experts in your industry are saying,
    and connect with creators, artists, and celebrities.</p>
 <p><b>Utility:</b> Get commuter info and updates, receive disaster updates and support, and reach
   customer service agents without having to call.</p>
</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title,'Home') %>
<h1>Pithugram</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/new.html.erb
<% provide(:title,'Sign Up') %>
<h1>Sign Up </h1>
<div class="container">
  <div class="jumbotron">
      <%= form_for @user do |t| %>
    <%= render 'shared/error_messages' %>
        <div class="form-group">
      <%= t.label :name %>
      <%= t.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
      <%= t.label :email %>
      <%= t.email_field :email, class: "form-control" %>
</div>
<div class="form-group">
      <%= t.label :password %>
      <%= t.password_field :password, class: "form-control" %>
</div><div class="form-group">
      <%= t.label :password_confirmation , 'Confirmation' %>
      <%= t.password_field :password_confirmation, class: "form-control" %>
</div><br/>
      <%= t.submit "Submit", class: "btn btn-default" %>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>SHOW USER </h1>
<div class="container">
<div class= "center jumbotron">
<p><b>Name:</b><%= @user.name %></p>
<p><b>Email:</b><%= @user.email %></p>
</div>
</div>